spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bsiep?serverTimezone=CET&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root
    password: root
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      certSignReq: CERT_SIGN_REQ
application:
  welcome:
    message: "Hi there."
